---
apiVersion: v1
kind: Service
metadata:
  name: movie-info-service
  namespace: default
  labels:
    app: movie-info
    type: backend
spec:
  selector:
    app: movie-info
    type: backend
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-info-deployment
  namespace: default
  labels:
    app: movie-info
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-info
      type: backend
  template:
    metadata:
      labels:
        app: movie-info
        type: backend
    spec:
      containers:
      - name: movie-info-service
        image: 2121994/movie-info-service
        ports:
        - containerPort: 8082